# Change these first
owner: SamuelQuinones # Your GitHub organization or username, where this repository lives
repo: recipe-room-upptime # The name of this repository

sites:
  - name: Recipe Room App
    url: https://reciperoom.net
    icon: https://reciperoom.net/favicon.ico

status-website:
  favicon: https://reciperoom.net/favicon.ico
  faviconSvg: https://reciperoom.net/logo.svg
  cname: status.reciperoom.net
  logoUrl: https://raw.githubusercontent.com/SamuelQuinones/recipe-room-upptime/refs/heads/master/assets/recipe-room-logo.svg
  name: Recipe Room
  introTitle: "**Recipe Room** is used to create, share, and store your collection of recipes!"
  introMessage: This page reports on the statuses and potential ouages of Recipe Room and all associated services in real-time.
  css: "@media (prefers-color-scheme:dark){.logo>img{filter:invert(100%)}}"
  navbar:
    - title: Status
      href: /

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
