# Change these first
owner: SamuelQuinones # Your GitHub organization or username, where this repository lives
repo: recipe-room-upptime # The name of this repository

sites:
  - name: Recipe Room App
    url: https://reciperoom.net

status-website:
  favicon: https://reciperoom.net/favicon.ico
  # faviconSvg: https://reciperoom.net/logo.svg
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.reciperoom.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/SamuelQuinones/recipe-room-upptime/refs/heads/master/assets/recipe-room-logo.svg
  name: Recipe Room
  introTitle: "**Recipe Room** is used to create, share, and store your collection of recipes!"
  introMessage: This page reports on the status of Recipe Room and all associated services in real-time. Outages will also be reported with live updates. Made with [Upptime](https://github.com/upptime/upptime)
  css: "@media (prefers-color-scheme:dark){.logo>img{filter:invert(100%)}}"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
